# Generated by Django 2.0.6 on 2018-07-10 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('crime_rate', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liability_property', models.PositiveIntegerField(blank=True, default=0)),
                ('liability_person', models.PositiveIntegerField(blank=True, default=0)),
                ('liability_accident', models.PositiveIntegerField(blank=True, default=0)),
                ('personal_injury', models.PositiveIntegerField(blank=True, default=0)),
                ('comprehensive', models.PositiveIntegerField(blank=True, default=0)),
                ('collision', models.PositiveIntegerField(blank=True, default=0)),
                ('uninsured_property', models.PositiveIntegerField(blank=True, default=0)),
                ('uninsured_person', models.PositiveIntegerField(blank=True, default=0)),
                ('uninsured_accident', models.PositiveIntegerField(blank=True, default=0)),
                ('under_property', models.PositiveIntegerField(blank=True, default=0)),
                ('under_person', models.PositiveIntegerField(blank=True, default=0)),
                ('under_accident', models.PositiveIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=40, null=True)),
                ('policy_number', models.CharField(max_length=30, null=True)),
                ('effective_date', models.DateField(null=True)),
                ('expiration_date', models.DateField(null=True)),
                ('vin', models.CharField(max_length=17, null=True)),
                ('mileage', models.PositiveIntegerField(blank=True, default=0)),
                ('coverage', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='switchinweb.Coverage')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='general', max_length=40)),
                ('mileage', models.PositiveIntegerField(blank=True, default=0)),
                ('document', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('name', models.CharField(max_length=12, null=True)),
                ('name_abbrev', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('avg_property', models.IntegerField(default=0)),
                ('avg_injury', models.IntegerField(default=0)),
                ('pop_vehicle', models.CharField(default='general', max_length=46)),
                ('min_coverage', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='switchinweb.Coverage')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('name', models.CharField(max_length=46, primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=20, null=True)),
                ('model', models.CharField(max_length=20, null=True)),
                ('year', models.PositiveIntegerField(blank=True, default=1990)),
                ('mass', models.PositiveIntegerField(blank=True, default=0)),
                ('iso_coll', models.PositiveIntegerField(blank=True, default=5)),
                ('iso_comp', models.PositiveIntegerField(blank=True, default=5)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='switchinweb.State'),
        ),
    ]
