# Generated by Django 2.0.6 on 2018-06-27 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liability_property', models.CharField(max_length=200)),
                ('liability_injury', models.CharField(max_length=200)),
                ('personal_injury', models.CharField(max_length=200)),
                ('comprehensive', models.CharField(max_length=200)),
                ('collision', models.CharField(max_length=200)),
                ('uninsured_injury', models.CharField(max_length=200)),
                ('uninsured_property', models.CharField(max_length=200)),
                ('road_service', models.CharField(max_length=200)),
                ('rental', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('policy_number', models.IntegerField()),
                ('effective_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('vin', models.IntegerField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='switchinweb.Policy')),
            ],
        ),
        migrations.AddField(
            model_name='coverage',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='switchinweb.Policy'),
        ),
    ]
