# Generated by Django 2.0.6 on 2018-07-10 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('switchinweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='min_coverage',
        ),
    ]
