# Generated by Django 2.0.6 on 2018-06-28 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('switchinweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='coverage',
            name='policy',
        ),
        migrations.AddField(
            model_name='policy',
            name='coverage',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='switchinweb.Coverage'),
        ),
    ]
