# Generated by Django 2.0.6 on 2018-07-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchinweb', '0002_remove_state_min_coverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='avg_mileage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='state',
            name='avg_injury',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='state',
            name='avg_property',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
