# Generated by Django 2.0.6 on 2018-06-29 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('switchinweb', '0002_auto_20180628_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverage',
            name='rental',
        ),
        migrations.RemoveField(
            model_name='coverage',
            name='road_service',
        ),
        migrations.RemoveField(
            model_name='coverage',
            name='uninsured_property',
        ),
        migrations.RemoveField(
            model_name='policydoc',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='policy',
        ),
        migrations.AddField(
            model_name='policy',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='vehicle',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='switchinweb.Vehicle'),
        ),
        migrations.AlterField(
            model_name='policydoc',
            name='document',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
