# Generated by Django 2.0.6 on 2018-06-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchinweb', '0003_auto_20180629_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(max_length=30),
        ),
    ]
