# Generated by Django 2.0.6 on 2018-07-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchinweb', '0003_auto_20180710_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='vehicle',
            field=models.CharField(default='general', max_length=46),
        ),
    ]
