# Generated by Django 2.0.6 on 2018-06-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchinweb', '0004_auto_20180629_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_number',
            field=models.CharField(max_length=30),
        ),
    ]
