# Generated by Django 2.0.6 on 2018-06-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchinweb', '0005_auto_20180629_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='effective_date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='policy',
            name='expiration_date',
            field=models.CharField(max_length=30),
        ),
    ]
