# Generated by Django 2.0.6 on 2018-07-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchinweb', '0006_auto_20180710_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='uninsured_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
