# Generated by Django 2.0.6 on 2018-07-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchinweb', '0007_state_uninsured_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
