# Generated by Django 2.0.6 on 2018-07-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchinweb', '0008_auto_20180712_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
