# Generated by Django 2.0.6 on 2018-07-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchinweb', '0009_auto_20180712_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
